title: "Jiwonâ€™s Bioinformatics Study ðŸ§¬"
description: "A journey to become a Bioinformatics Scientist"
theme: minima
baseurl: "/bioinformatics-study"
url: https://bora-dori.github.io/bioinformatics-study
